### ISSUE TITLE
Teste

### ISSUE THREAD

**Issue by eduardoadcj** [IntegratorProject/RentMovieSystem#1]

**Comment by GuxtavoLiu** [comment]
Tendi

Enviado do meu iPhone

Em 24 de ago de 2018, à(s) 19:46, Eduardo A. Cruz Junior <notifications@github.com<mailto:notifications@github.com>> escreveu:


To fazendo um teste pra testar

**Comment by eduardoadcj** [comment]
era so pra teste mesmo
