### ISSUE TITLE
A respeito de locações

### ISSUE THREAD

**Issue by eduardoadcj** [IntegratorProject/RentMovieSystem#2]
Quando uma locação é concluída, é interessante permitir que o usuário exclua os registros da locação do banco de dados?

**Comment by ramosmatheus** [comment]
Eu acho que não, pois se uma pessoa é de atrasar as entregas você tendo os registros na próxima locação você pode diminuir a data de entrega ou fazer algum tipo de aviso para esse cliente.

**Comment by eduardoadcj** [comment]
Então fechado galera, vo colocar pra esconder o botão que tinha essa funcionalidade.
